@startuml

struct Request{
    DRIVER
    Transport
}


class CoAPI_server{

.. resource handling ..
    register_resource()
    remove_resource() 

.. make_Request ..
    request init_request(uri, DRIVER)
    add_option()
    add_payload()
    
}
class gcoap_driver{
    init_request()
    add_option()
    add_payload()
}

class libCoAP_driver{
    init_request()
    add_option()
    add_payload()
}

CoAPI_server::init_request -> libCoAP_driver::init_request
CoAPI_server::init_request -> gcoap_driver::init_request

@enduml