@startuml
Application -> CoAPI: useDriver(transport_udp, gcoap_driver)

Application -> CoAPI: register_resource(\npath, allowedMethods, allowedTransports,\nlinkParams, handler)

Application -> CoAPI: start_server()

CoAPI -> GCOAP_Handler: start_server(resource_pool)

GCOAP_Handler -> GCOAP_Handler: startServer(resourcePool)

@enduml