@startuml
package "Application Layer"{
    [Application]
}

package "CoAPI"{
    [API_Entry]
    gcoap_handler -up- [API_Entry]:useTransport = UDP
    LibCoAP_handler -up- [API_Entry]:useTransport = TCP
}

LibCoAP_handler -down-> LibCoAP: Callback
gcoap_handler -down-> gcoap: Callback

Application -down-> API_Entry
@enduml